### Basic information
site_name: dbverse

### Repo information
repo_url: https://github.com/drieslab/dbverse
repo_name: dbverse

### Plugins
plugins:
  - search
  - mermaid2

### Navigation tree
nav:
  - Home: README.md
  - Packages: packages.md
  - Overview: overview.md
  - About: about.md
  - Code of Conduct: conduct.md
  - Contribute: contribute.md


### Theme
theme:
  name: material
  language: en
  palette:
    primary: black
    accent: light blue
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.tabs
    - navigation.expand
    - navigation.sections
    - navigation.top
    - toc.integrate
    - toc.tabs
    - toc.sections
    - footer
